server:
  port: 8095

spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://DESKTOP-7CFDUUP\SQLEXPRESS;databaseName=jwt_test;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
  sql:
    init:
      platform: mssql
  mail:
    host: smtp.gmail.com
    port: 587
    username: santivarela.agent@gmail.com
    password: xcrz fvhd fghr veeu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
santi:
  app:
    jwtSecret: ijEjr4sgDxL2UV10ySRfEP2FuwKVNnkVEqOUSutpUSV764Is6J7kceF7jR5tvQlQNGH1yV5AWFin6KMeJoatjw
    jwtExpirationMs: 60000
    jwtRefreshExpirationMs: 3600000
    deadlineTransportationAssignmentMs: 60000
    mail:
      username: santivarela.agent@gmail.com

upload:
  path: C:/Users/Santiago Varela/Pictures/spring_boot_img/

gcp:
  firebase:
    service-account: classpath:firebase/firebase-service-account.json

google:
  maps:
    apikey: AIzaSyB41DRUbKWJHPxaFjMAwdrzWzbVKartNGg

bing:
  maps:
    apikey: AltqUH2HBpugYCVAkuvz-jM6YAdBdiTmDBr0mcLx9QTU6Bt6TozzweZT7oBQMC2I


