server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
spring:
  devtools:
    restart:
      enabled: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cpg138v79t8c73ebhpc0-a/database_q1xd
    username: database_q1xd_user
    password: 6TwuKpN8nhDP5vXsDWMUjz2ksojz0szc
  jpa:
    hibernate:
      ddl-auto: create-drop
    #      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: santivarela.agent@gmail.com
    password: xcrz fvhd fghr veeu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    time-zone: GMT+7
santi:
  app:
    jwtSecret: ijEjr4sgDxL2UV10ySRfEP2FuwKVNnkVEqOUSutpUSV764Is6J7kceF7jR5tvQlQNGH1yV5AWFin6KMeJoatjw
    jwtExpirationMs: 60000
    jwtRefreshExpirationMs: 3600000
    deadlineTransportationAssignmentMs: 180000
    mail:
      username: santivarela.agent@gmail.com

upload:
  path: C:/Users/Santiago Varela/Pictures/spring_boot_img/

gcp:
  firebase:
    service-account: classpath:firebase/firebase-service-account.json

google:
  maps:
    apikey: AIzaSyB41DRUbKWJHPxaFjMAwdrzWzbVKartNGg

bing:
  maps:
    apikey: AltqUH2HBpugYCVAkuvz-jM6YAdBdiTmDBr0mcLx9QTU6Bt6TozzweZT7oBQMC2I

# swagger-ui custom path
springdoc.swagger-ui.path: /swagger-ui.html




