INSERT INTO roles(name) VALUES('ROLE_USER');
INSERT INTO roles(name) VALUES('ROLE_MODERATOR');
INSERT INTO roles(name) VALUES('ROLE_ADMIN');
INSERT INTO roles(name) VALUES('ROLE_PRODUCER');
INSERT INTO roles(name) VALUES('ROLE_TRANSPORTER');
INSERT INTO roles(name) VALUES('ROLE_CUSTOMER');


INSERT INTO states(name) VALUES('CREATED');
INSERT INTO states(name) VALUES('ACCEPTED');
INSERT INTO states(name) VALUES('TRANSPORTER_ASSIGNED');
INSERT INTO states(name) VALUES('PACKAGING');
INSERT INTO states(name) VALUES('PROCESSING_PAYMENT');
INSERT INTO states(name) VALUES('SHIPPED');
INSERT INTO states(name) VALUES('DELIVERED');
INSERT INTO states(name) VALUES('CANCELED');
