INSERT INTO roles(name) VALUES('ROLE_USER');
INSERT INTO roles(name) VALUES('ROLE_MODERATOR');
INSERT INTO roles(name) VALUES('ROLE_ADMIN');
INSERT INTO roles(name) VALUES('ROLE_PRODUCER');
INSERT INTO roles(name) VALUES('ROLE_TRANSPORTER');
INSERT INTO roles(name) VALUES('ROLE_CUSTOMER');